#! /bin/sh 

for NR in 1 2 3 4 5 6;
do

readas=read_${NR}.fastq

cutadapt -a AGATTGGAAGAGTGTCATGTAGGGAAAGAGTG $readas | cutadapt -g GTTACATCTGGTAGTCAGTCTCCAATAAATATATAAAA - > read_${NR}cutadapt.fastq

done

~/Desktop/bioinfo/FastQC/fastqc ~/Desktop/bioinfo/readai/final/*cutadapt.fastq
