#! /bin/sh 

ref=*.fa

for i in Ion*fastq;
do

/home/povilas/tools/fastqc/fastqc $i

ID=$(echo $i | cut -f 2 -d "_")

cutadapt -g GTTACATCTGGTAGTCAGTCTCCAATAAATATATAAAA --discard-untrimmed $i | cutadapt -m 80 - > cut5_${ID}.fastq

/home/povilas/tools/fastqc/fastqc cut5_${ID}.fastq

cutadapt -a AGATTGGAAGAGTGTCATGTAGGGAAAGAGTG cut5_${ID}.fastq > cut5_3_${ID}.fastq

/home/povilas/tools/fastqc/fastqc cut5_3_${ID}.fastq

/home/povilas/tools/fastx/fastq_quality_trimmer -t 20 -l 80 -Q33 -i cut5_3_${ID}.fastq -o cut5_3_qt_${ID}.fastq

/home/povilas/tools/fastqc/fastqc cut5_3_qt_${ID}.fastq

done

bwa index $ref

for i in cut5_3_qt_*fastq;
do

bwa mem $ref $i | samtools view -b -S - | bedtools bamtobed -i - > mapped${i}.bed

done
